name: Cloud SQL Maintenance

on:
  workflow_dispatch:

## Uncomment schedule when need to enable.
  # schedule:
  #   - cron:  '15 12 * * *'

  pull_request:
    branches:
      - 'main'
    paths: 'scripts/maintenance-upgrade.sh'

env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  BOT_TOKEN: ${{ secrets.BOT_AUTH_TOKEN }}
      
jobs:
  cloudsql-maintenance:
    runs-on: cloudsql-maintenance-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
        service_account: ${{ vars.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

    - name: Run Cloud SQL Maintenance 
      run:
       /bin/sh /home/lostinopensrc/cloudsql-maintenance-upgrade/_work/cloudsql-maintenance-upgrade/cloudsql-maintenance-upgrade/scripts/maintenance-upgrade.sh